services:
  postgres:
    env_file:
      - ../.env
    image: postgres:15
    container_name: ${CONTAINER_PREFIX:-cvapp}_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: ${POSTGRES_DB:-cvdb}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-cvdb}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - ${POSTGRES_EXTERNAL_PORT:-5433}:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - app_network

  redis:
    env_file:
      - ../.env
    image: redis:latest
    container_name: ${CONTAINER_PREFIX:-cvapp}_redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data
    ports:
      - ${REDIS_EXTERNAL_PORT:-6380}:6379
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  personal-task-manager:
    env_file:
      - ../.env
    build:
      context: ..
      dockerfile: ./Dockerfile
    container_name: ${CONTAINER_PREFIX:-cvapp}_core
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB:-cvdb}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER:-postgres}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - ${CV_EXTERNAL_PORT:-8080}:8080
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - app_network

  nginx:
    env_file:
      - ../.env
    image: nginx:latest
    container_name: ${CONTAINER_PREFIX:-cvapp}_nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx:/var/log/nginx
    ports:
      - ${NGINX_EXTERNAL_PORT:-80}:80
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
